### ISSUE TITLE
Installation Fails in Windows 8

### ISSUE THREAD

**Issue by awol** [exxeleron/qXL#9]
Hi, Trying to install either of the msi packages on my windows 8 machine fails with "...installation ended prematurely". Any thoughts on how to work around this. I don't have the tools to build everything at the  moment and would rather not have to. Where can I find the "parts" that the installer is trying to install.
Thanks,

**Comment by bartiosze** [comment]
Hi,

I'm running Win8 box myself and did not experience any problems with installation. 

Can you please verify the checksum of your install? Should be A86F311DA7D698E6212FD1AA4AC9345D

You can do it in PowerShell:

    Get-FileHash <filepath> -Algorithm MD5

**Comment by awol** [comment]
(Sorry about the formatting)

    Get-FileHash .\qXL-1.0.0.61.msi -Algorithm MD5
    Algorithm       Hash                                                                  
    ---------       ----
    MD5             A86F311DA7D698E6212FD1AA4AC9345D

**Comment by awol** [comment]
Problem solved. Multiple VMs tried the one without excel installed. Works fine when excel is actually present!!!!
